### ISSUE TITLE
Slow function 

### ISSUE THREAD

**Issue by JamesFB1** [JamesFB1/Gopher.Fit#1]
This part of the bootstrap function is really slow as it fits the model 1000 times for each: Intercept, Prev, and Sigmasq. 

summarize(Intercept = run_model(data = data,example = "tortoise")$beta[[1]],
            Prev = run_model(data = data,example = "tortoise")$beta[[2]],
            Sigmasq = run_model(data = data,example = "tortoise")$sigmasq)

**Comment by doracao** [comment]
I changed this part of the function to

summarize(tidy(suppressMessages(glmer(shells ~ prev + offset(log(Area)) + factor(year) + (1|Site),
                                          family = poisson, data = data))), .groups = "drop")

It took roughly 3 minutes to run. 

I also had to change the portion below computing bootstrap standard error and CI for Intercept, Prev and Sigmasq.

I compared the values obtained using your method and this method, see below (Intercept1, Prev1 and Sigmasq1 were computed using your method). Intercept and Intercept1 and Prev and Prev1 look similar but I might be computing the bootstrap standard error and CI for Sigmasq wrong because the estimates look different.

> Intercept1
# A tibble: 1 × 3
     SE Lower95 Upper95
  <dbl>   <dbl>   <dbl>
1 0.315   -3.89   -2.68
>   Intercept
# A tibble: 1 × 3
     SE Lower95 Upper95
  <dbl>   <dbl>   <dbl>
1 0.302   -3.84   -2.67
>   
>   Prev1
# A tibble: 1 × 3
       SE Lower95 Upper95
    <dbl>   <dbl>   <dbl>
1 0.00559  0.0105  0.0318
>   Prev
# A tibble: 1 × 3
       SE Lower95 Upper95
    <dbl>   <dbl>   <dbl>
1 0.00535  0.0109  0.0312
>   
>   Sigmasq1
# A tibble: 1 × 3
      SE  Lower95 Upper95
   <dbl>    <dbl>   <dbl>
1 0.0876 8.48e-18   0.372
>   Sigmasq
# A tibble: 1 × 3
     SE       Lower95 Upper95
  <dbl>         <dbl>   <dbl>
1 0.163 0.00000000266   0.618

**Comment by JamesFB1** [comment]
I think I managed to get it using some dplyr functions to extract the correct values from the output of estimation functions.
